---
name: MegaLinter

on:
  pull_request:
    branches:
      - main
      - master
      - feature/**/main
      - feature/**/master

env:
  APPLY_FIXES: none

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ghcr:
    runs-on: ubuntu-latest
    name: GHCR
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: MegaLinter
        uses: ./
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE: SHELL,YAML,MARKDOWN
          DISABLE_LINTERS: BASH_SHFMT
        with:
          registry: ghcr.io
          flavor: documentation
  hub:
    runs-on: ubuntu-latest
    name: Docker Hub
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: MegaLinter
        uses: ./
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE: SHELL,YAML,MARKDOWN
          DISABLE_LINTERS: BASH_SHFMT
        with:
          registry: docker.io
          flavor: documentation
